# Generated by Django 2.2.18 on 2021-09-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0034_student_favorite_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isMock', models.NullBooleanField(default=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('lifespan', models.IntegerField(default=0)),
            ],
        ),
    ]
