# Generated by Django 2.2.18 on 2021-09-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0035_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='students',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
