# Generated by Django 2.2.18 on 2021-09-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0036_mock_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mock',
            old_name='lifespan',
            new_name='num1',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='isMock',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='name',
        ),
        migrations.AddField(
            model_name='mock',
            name='num2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mock',
            name='num3',
            field=models.IntegerField(default=0),
        ),
    ]
