# Generated by Django 2.2.18 on 2021-09-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0037_auto_20210929_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mock',
            name='num1',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mock',
            name='num2',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='mock',
            name='num3',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
